import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { Lato } from '@next/font/google';
import Home from "./page";
import Dashboard from "./pages/Dashboard";

const lato = Lato({
  subsets: ['latin'], // Specify subsets you need
  weight: ['400', '700'], // Optional: Specify font weights
  variable: '--font-lato', // Add CSS variable for custom usage
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.variable}>
        <SidebarProvider> 
        {/* Fixed Header */}
         <Header /> 
         <Dashboard/>

        {/* Main Content */}
        <main > {children}</main>

        {/* Fixed Footer */}
        {/* <Footer /> */}
        </SidebarProvider>
      </body>
    </html>
  );
}
