/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/homepage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/introScreen1`; params?: Router.UnknownInputParams; } | { pathname: `/screens/introScreen2`; params?: Router.UnknownInputParams; } | { pathname: `/screens/introScreen3`; params?: Router.UnknownInputParams; } | { pathname: `/screens/loginPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/onboardingpage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/registration`; params?: Router.UnknownInputParams; } | { pathname: `/screens/splashScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/homepage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/introScreen1`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/introScreen2`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/introScreen3`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/loginPage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/onboardingpage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/registration`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/splashScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/navigation/AppNavigator${`?${string}` | `#${string}` | ''}` | `/screens/homepage${`?${string}` | `#${string}` | ''}` | `/screens/introScreen1${`?${string}` | `#${string}` | ''}` | `/screens/introScreen2${`?${string}` | `#${string}` | ''}` | `/screens/introScreen3${`?${string}` | `#${string}` | ''}` | `/screens/loginPage${`?${string}` | `#${string}` | ''}` | `/screens/onboardingpage${`?${string}` | `#${string}` | ''}` | `/screens/registration${`?${string}` | `#${string}` | ''}` | `/screens/splashScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/homepage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/introScreen1`; params?: Router.UnknownInputParams; } | { pathname: `/screens/introScreen2`; params?: Router.UnknownInputParams; } | { pathname: `/screens/introScreen3`; params?: Router.UnknownInputParams; } | { pathname: `/screens/loginPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/onboardingpage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/registration`; params?: Router.UnknownInputParams; } | { pathname: `/screens/splashScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
